### ISSUE TITLE
flashblade.purefb_dns errors out on KeyError: 'service'

### ISSUE THREAD

**Issue by mdkent** [Pure-Storage-Ansible/FlashBlade-Collection#363]
**Describe the bug**
After bumping to 1.20.0 we're seeing a failure in the flashblade.purefb_dns module. This was fine on 1.19.2.

It fails with 

> in main\n  File \"/var/folders/f1/_00jhynx1x59dkrpk2g2f4mc0000gn/T/ansible_purestorage.flashblade.purefb_dns_payload_76cteant/ansible_purestorage.flashblade.purefb_dns_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_dns.py\", line 172, in update_multi_dns\nKeyError: 'service'\n"

[Exact line](https://github.com/Pure-Storage-Ansible/FlashBlade-Collection/blob/20e4c8b9dac0f515e5b1e3af9f501b4c3ba778f6/plugins/modules/purefb_dns.py#L172).

**To Reproduce**
```
    - name: "{{ datacenter }} - DNS servers"
      purestorage.flashblade.purefb_dns:
        fb_url: "{{ fb_url }}"
        api_token: "{{ api_token }}"
        domain: foo.com
        nameservers:
          - 10.0.0.1
```
Looking at the code, it looks like `module.params["service"]` isn't given a default value in `main()`. 

I tried fixing it but I'm a bit confused on what the value should be as the API looks to expect a list of services like `management, data`.

**Comment by sdodsley** [comment]
Looks like something got missed in the latest update for this module.
We will have aloo and try and get a fix out ASAP

**Comment by sdodsley** [comment]
@mdkent here is a fix. I'm not in a position t ocheck this, so if you could please try it out and let me know if it works as expected.
If it does I will release a 1.20.1 patch for the Collection.

**Comment by mdkent** [comment]
Thanks for the quick branch! I'm afraid it fails with:
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "disable_warnings": false,
            "domain": "<redacted>",
            "fb_url": "<redacted>",
            "name": "management",
            "nameservers": [
                "10.0.0.1"
            ],
            "service": "management",
            "source": null,
            "state": "present"
        }
    },
    "msg": "Changing service type is not permitted"
}
```
I tried changing the service to `data` as well but that fails in the same way.

Doing a bit of debugging it looks like `current_dns.services` is set to 
```
    [
        "management",
        "data"
    ]
```
Which seems to be the default as I can't specify or edit the `service` via the UI.

**Comment by sdodsley** [comment]
Got it - will work on fixing that

**Comment by sdodsley** [comment]
OK - I think that should fix it.

**Comment by mdkent** [comment]
Okay, closer. The `--check` passes now, but adding a new nameserver fails with:

> File \"/var/folders/f1/_00jhynx1x59dkrpk2g2f4mc0000gn/T/ansible_purestorage.flashblade.purefb_dns_payload_h_utmrvm/ansible_purestorage.flashblade.purefb_dns_payload.zip/ansible_collections/purestorage/flashblade/plugins/modules/purefb_dns.py\", line 195, in update_multi_dns\nTypeError: 'NoneType' object is not callable\n"

Looking at py-pure-client it looks like it should be `sources=ReferenceNoId(module.params["source"]),` instead of `source=`, but that change alone doesn't seem to fix it. Just removing line 195 does fix it though and my nameserver update works.

Guessing you just need to handle source being empty, as it is for the default interface:

<img width="826" alt="Image" src="https://github.com/user-attachments/assets/02392f70-eb1a-4625-8e67-7be60004599e" />

**Comment by mdkent** [comment]
Okay! It works. I was able to add and remove a dns server:

```
PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

All done 🚀
```
Just an fyi that your PR has `*.swp` file in it. Might want to add that to `.gitignore`.
